src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="La date d'arrivée doit être au format date")
     * @Assert\GreaterThan(
     *     "today",
     *     message="La date d'arrivée doît être ultérieure à la date d'aujourd'hui",
     *     groups={"front"}
     * )
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="La date d'arrivée doit être au format date")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * Callback appelé à chaque fois que l'on fait une réservation
     *
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     *
     * @return void
     */
    public function prePersist()
    {
        if (empty($this->createdAt)) {
            $this->createdAt = new \DateTime();
        }

        if (empty($this->amount)) {
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    public function isBookableDates()
    {
        //Il faut connaître les dates impossible pour l'annonce
        $notAvailableDays = $this->ad->getNotAvailableDays();
        //Il faut comparer les dates choisies avec les dates impossibles
        $bookingDays = $this->getDays();

        $formatDay = function ($day){
            return $day->format('Y-m-d');
        };

        //transformation de chaque valeur de chaque tableau en simple string, plus simple à comparer
        $days         = array_map($formatDay, $bookingDays);
        $notAvailable = array_map($formatDay, $notAvailableDays);

        foreach ($days as $day) {
            if (array_search($day, $notAvailable) !== false) return false;
        }

        return true;
    }

    /**
     * Permet de récupérer un tableau des journées qui correspondent à ma réservation
     *
     * @return array un tableau d'objet DateTime représentant les jours de la réservation
     */
    public function getDays()
    {
        $result = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24 * 60 * 60
        );

        return array_map(function($dayTimestamp){
           return new \DateTime(date('Y-m-d', $dayTimestamp));
        }, $result);
    }

    /**
     * @return mixed
     */
    public function getDuration()
    {
        //renvoie un objet DateInterval
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"email"},
 *     message="Cet email est déjà pris"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseinger votre nom de famille")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez renseigner un email valide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message="Veuillez donner une url valide")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @Assert\EqualTo(
     *     propertyPath="hash",
     *     message="Vous n'avez pas correctement confirmé votre mot de passe"
     * )
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="10", minMessage="Votre intro doit faire au moins 10 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min="100", minMessage="Votre description doit faire au moin 100 caractères")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    public function getFullName()
    {
        return "{$this->firstName} {$this->lastName}";
    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Permet d'initaliser le slug à la création/maj de l'entité
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function initializeSlug()
    {
        if (empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName . ' ' . $this->lastName);
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @inheritDoc
     */
    public function getRoles()
    {
        //on transforme le trableau d'entité de rôles en tableau simple de rôles
        $roles = $this->userRoles->map(
            function($role){
                return $role->getTitle();
            }
        )->toArray();
        $roles[] = 'ROLE_USER';

        return $roles;
    }

    /**
     * @inheritDoc
     */
    public function getPassword()
    {
        return $this->hash;
    }

    /**
     * @inheritDoc
     */
    public function getSalt()
    {
        // useless avec bcrypt
    }

    /**
     * @inheritDoc
     */
    public function getUsername()
    {
        return $this->email;
    }

    /**
     * @inheritDoc
     */
    public function eraseCredentials()
    {
        // inutile car pas de données sensibles stockées dans l'objet
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BookingController extends AbstractController
{
    /**
     * @Route(
     *     "/ads/{slug}/book",
     *     name="booking_create"
     * )
     * @IsGranted("ROLE_USER")
     */
    public function book(Ad $ad, Request $request, EntityManagerInterface $em)
    {
        $booking = new Booking();
        $form    = $this->createForm(BookingType::class, $booking);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //on relie la réservation à l'utilisateur courant et à l'annonce reçue en param
            $booking->setBooker($this->getUser())
                ->setAd($ad);

            //Si les dates ne sont pas dispos, message d'erreur
            if (!$booking->isBookableDates()) {
                $this->addFlash(
                    'warning',
                    "Les dates que vous avez choisi sont déjà prises."
                );
            }else{
                $em->persist($booking);
                $em->flush();
                return $this->redirectToRoute('booking_show', [
                    'id'        => $booking->getId(),
                    'withAlert' => true
                ]);
            }
        }

        return $this->render('booking/book.html.twig', [
            'ad'   => $ad,
            'form' => $form->createView()
        ]);
    }

    /**
     * Permet d'afficher la page d'une réservation
     *
     * @Route(
     *     "/booking/{id}",
     *     name="booking_show"
     * )
     *
     * @param Booking $booking
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return Response
     */
    public function show(Booking $booking, Request $request, EntityManagerInterface $em)
    {
        $comment = new Comment();

        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setAd($booking->getAd())
                ->setAuthor($this->getUser());

            $em->persist($comment);
            $em->flush();

            $this->addFlash(
                'success',
                "Votre commentaire a bien été pris en compte"
            );
        }

        return $this->render('booking/show.html.twig', [
            'booking' => $booking,
            'form'    => $form->createView()
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réserver l'annonce {{ ad.title }}{% endblock %}

{% block stylesheets %}
    {# bootstrapt datepicker uxsolutions#}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css">
{% endblock %}

{% block body %}
    <div class="container">
        <h1>Réservez pour l'annonce : <em>{{ ad.title }}</em></h1>

        <p>Vous êtes sur le point de réserver le bien de <strong>{{ ad.author.fullName }}</strong>, dites nous tout, on s'ouccupe du reste !</p>

        {{ form_start(form) }}
        <div class="alert alert-light">
            <h4>Commencez par nous dire quelles sont les dates qui vous intéressent !</h4>
            <div class="row">
                <div class="col">
                    {{ form_row(form.startDate) }}
                </div>
                <div class="col">
                    {{ form_row(form.endDate) }}
                </div>
            </div>
            <h4 class="mt-2">Montant du séjour : <span id="amount">...</span> &euro;</h4>
            <span id="days">0</span> nuit(s) à {{ ad.price | number_format(2, ',', ' ') }} &euro; par nuit

            <h4 class="mt-3">Vous avez un commentaire ?</h4>
            {{ form_row(form.comment) }}
        </div>


        <h2>Vous avez terminé !</h2>
        <button type="submit" class="btn btn-success">Je réserve</button>

        {{ form_end(form) }}

    </div>
{% endblock %}

{% block javascripts %}
    {# bootstrapt datepicker uxsolutions#}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js" integrity="sha256-tW5LzEC7QjhG0CiAvxlseMTs2qJS7u3DRPauDjFJ3zo=" crossorigin="anonymous"></script>

    <script>
        $(document).ready(function () {
            $('#booking_startDate, #booking_endDate').datepicker({
                format: "dd/mm/yyyy",
                datesDisabled: [
                    {% for day in ad.notAvailableDays %}
                        "{{ day.format('d/m/Y') }}",
                    {% endfor %}
                ],
                startDate: new Date() //interdit de réserver avant la date d'aujourd'hui
            });

            $('#booking_startDate, #booking_endDate').on('change', calculateAmount);

        });

        function calculateAmount() {
            //Récupération des dates, en convertissant à la volée une date fr (dd/mm/YYYY) en date américaine (YYYY-mm-dd) pour qu'elle soit gérable par les objets JS Date()
            const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
            const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));

            if (startDate && endDate && startDate < endDate) {
                //nombre de millisecondes dans un jour
                const DAY_TIME = 24 * 60 * 60 * 1000;
                //soustraction de timeStamps
                const interval = endDate.getTime() - startDate.getTime();
                //nb de jours dans l'interval séléctionné par l'utilisateur
                const days = interval / DAY_TIME;
                const amount = days * {{ ad.price }};
                //mise à jour du span contenant le nombre de jour réservés
                $('#days').text(days);
                //mise à jour du montant, avec la méthode toLocaleString() appelable sur les number, qui permet d'afficher ici des virgules à la place des points
                $('#amount').text(amount.toLocaleString('fr-FR'));

            }
        }

        console.log(new Date());
    </script>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réserveration n° {{ booking.id }}{% endblock %}

{% block body %}

    {% set ad = booking.ad %}
    {% set author = ad.author %}

    <div class="container">
        <h1 class="my-5">Votre réservation n° {{ booking.id }}</h1>
        {# Récupération du param withAlert en GET dans la Request#}
        {% if app.request.query.get('withAlert') %}
            <div class="alert alert-success">
                <h4 class="alert-heading">Bravo !</h4>
                <p>
                    Votre réservation auprès de
                    <strong>
                        <a href="{{ path('user_show', {'slug': author.slug}) }}">{{ author.fullName }}</a>
                    </strong>
                    pour l'annonce
                    <strong>
                        <a href="{{ path('ads_show', {'slug': ad.slug}) }}">{{ ad.title }}</a>
                    </strong>
                    a bien été prise en compte
                </p>
            </div>
        {% endif %}

        <div class="row">
            <div class="col">
                <div class="alert alert-light">
                    <h2>Détails</h2>
                    <dl class="row">
                        <dt class="col-md-4">Numéro</dt>
                        <dd class="col-md-8">{{ booking.id }}</dd>
                        <dt class="col-md-4">Date d'arrivée</dt>
                        <dd class="col-md-8">{{ booking.startDate | date('d/m/Y') }}</dd>
                        <dt class="col-md-4">Date de départ</dt>
                        <dd class="col-md-8">{{ booking.endDate | date('d/m/Y') }}</dd>
                        <dt class="col-md-4">Nombre de nuits</dt>
                        <dd class="col-md-8">{{ booking.duration }}</dd>
                        <dt class="col-md-4">Montant total</dt>
                        <dd class="col-md-8">{{ booking.amount | number_format(2, ',', ' ') }} &euro;</dd>
                        <dt class="col-md-4">Commentaire</dt>
                        <dd class="col-md-8">{{ booking.comment | default('Aucun commentaire') }}</dd>
                    </dl>

                    <hr>

                    <h2 class="alert-heading">Votre hôte</h2>

                    <div class="row mb-3">
                        <div class="col-3">
                            <img src="{{ author.picture }}" class="avatar avatar-medium" alt="Avatar de {{ author.fullName }}">
                        </div>
                        <div class="col-9">
                            <h4><a href="{{ path('user_show', {'slug': author.slug}) }}">{{ author.fullName }}</a></h4>

                            <span class="badge badge-primary">{{ author.ads | length }} annonces</span>
                        </div>
                    </div>
                    {{ author.description | raw }}
                    <a href="{{ path('user_show', {'slug': author.slug}) }}" class="btn btn-primary">Plus d'infos sur {{ author.firstName }}</a>

                    <div class="alert alert-light" id="comment">
                        <h2 class="alert-heading">Votre avis compte !</h2>
                        {% if date() > date(booking.endDate) %}
                            {% set comment = booking.ad.commentFromAuthor(app.user) %}
                            {% if comment is not null %}
                                <blockquote>
                                    {{ comment.content }}
                                </blockquote>
                                <strong>Note : strong</strong> {% include 'partials/rating.html.twig' with {'rating': comment.rating} %}
                            {% else %}
                                {{ form_start(form) }}
                                {{ form_widget(form) }}
                                <button type="submit" class="btn btn-success">Confirmer</button>
                                {{ form_end(form) }}
                            {% endif %}
                        {% else %}
                            <p>Vous ne pourrez pas noter cette anonce tant que votre voyage ne sera pas complet</p>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="alert alert-light">
                    <h2 class="alert-heading">Votre hébergement</h2>
                    
                    <h4>
                        <a href="{{ path('ads_show', {'slug': ad.slug}) }}">{{ ad.title }}</a>
                    </h4>

                    <img src="{{ ad.coverImage }}" alt="Image de {{ ad.title }}" class="img-fluid">

                    {{ ad.content | raw }}

                    <a href="{{ path('ads_show', {'slug': ad.slug}) }}" class="btn btn-primary">Plus d'infos</a>
                </div>
            </div>
        </div>

    </div>
{% endblock %}